### PR TITLE
phase 2 upload

### PR DESCRIPTION
**Pull request by John-A-Davies**
Changes to enable dataset editing.

### CODE REVIEW

**Review by 1000TurquoisePogs — COMMENTED** [review]
As in https://github.com/zowe/zlux-app-manager/pull/291 This looks good, but also looks subject to change on what ends up happening with ZSS

**Comment by John-A-Davies** [comment]
Not needed functionally, as the sessionID tryout has been superseded.

Kept in to allow compilation until all refs to sessionID tryout are removed.

**Review by DivergentEuropeans — APPROVED** [review]
Subject to change, but makes sense as is

**Comment by John-A-Davies** [comment]
It says "You’re not authorized to merge this pull request. "  As it's been approved, can an authorised user please merge it?  @1000TurquoisePogs

**Pull request closed without merging**
